# Generated by Django 3.2.6 on 2021-09-12 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleraccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent_market',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to='mainApp.subcategory'),
        ),
    ]
