# Generated by Django 3.2.6 on 2021-09-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0008_auto_20210901_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg',
            field=models.TextField(null=True),
        ),
    ]
