# Generated by Django 3.2.6 on 2021-09-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0009_message_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='recent_chat',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
