# Generated by Django 3.2.6 on 2021-09-04 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0010_chatroom_recent_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
