# Generated by Django 3.2.6 on 2021-09-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0012_auto_20210907_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
    ]
